### ISSUE TITLE
Problem with about,tags pages if there is more than 1 page.

### ISSUE THREAD

**Issue by nenadfilipovic** [jamesknelson/create-react-blog#18]
I have set to display 5 posts per page, in that case blog creates new page. When you go to that page about and tag page are not reachable, their path become /page/2/about and blog throws 404 error. I have fixed that by editing `create-react-blog/template/src/components/BlogIndexPage.js` file, in that file there are `./about` `./tags` `./rss.xml`. Just remove dots so it become `/about` `/tags` `/rss.xml` and it is working. Thanks for great blog. :)

**Comment by jamesknelson** [comment]
Glad it's working! Any chance you could submit a PR with the fix?

**Comment by nenadfilipovic** [comment]
Yea I submited request.
