### ISSUE TITLE
Error with header showing up on second index page.

### ISSUE THREAD

**Issue by nenadfilipovic** [jamesknelson/create-react-blog#20]
I have 10 posts in 2 pages and when I switch to second page blog doesn't recognize it is index page and shows pink header just like it show in posts. Problem is in 'src/routes/index.js in regex /^\/page\/\d+\/$/.test(req.path) which is expecting url to end with '/'. When I change to /^\/page\/\d+$/.test(req.path) it works like it should. I will send PR.

**Comment by jamesknelson** [comment]
Thanks! Just merged the PR.
